apiVersion: apps/v1
kind: Deployment
metadata:
  name: underwater-app-jenkins-deployment 
  labels:
    app: octopus-underwater-app
spec:
  selector:
    matchLabels:
        app: octopus-underwater-app
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: octopus-underwater-app
    spec:
      containers:
        - name: octopus-underwater-app
          image: 870165402940.dkr.ecr.us-east-1.amazonaws.com/octopus-underwater-app:latest
          ports:
            - containerPort: 8085
          imagePullPolicy: Always
# Service Type loadblancer 
---
apiVersion: v1
kind: Service
metadata:
  name: underwater-app-jenkins-service
spec:
  selector:
    app: octopus-underwater-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer
